# Generated by Django 4.2.2 on 2023-06-26 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cart_card_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='card_id',
        ),
    ]
