# Generated by Django 4.2.2 on 2023-06-26 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_cart_cart_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='cart_id',
        ),
    ]
